steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPO}/aioc-training:latest', '-f', 'Dockerfile.train', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPO}/aioc-training:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/job.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPO}/aioc-serving:latest', '-f', 'Dockerfile.serving', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPO}/aioc-serving:latest']
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'deploy', 'aioc-serving', '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPO}/aioc-serving:latest', '--region', '${_REGION}', '--platform', 'managed']

substitutions:
  _REGION: 'us-west1'  
  _GAR_REPO: 'aioc-docker-repo'  
  _ZONE: 'us-west1-b'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPO}/aioc-training:latest'
  # - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_GAR_REPO}/aioc-serving:latest'  