steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tinybert-train:$COMMIT_SHA', '-f', 'Dockerfile.train', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tinybert-train:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/job.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-b'  # Replace with your zone
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tinybert-serving:$COMMIT_SHA', '-f', 'Dockerfile.serving', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tinybert-serving:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'tinybert-serving', '--image', 'gcr.io/$PROJECT_ID/tinybert-serving:$COMMIT_SHA', '--region', 'us-west1', '--platform', 'managed']

# This substitutes the $COMMIT_SHA Cloud Build variable for the tag
images:
  - 'gcr.io/$PROJECT_ID/tinybert-train:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tinybert-serving:$COMMIT_SHA'