apiVersion: batch/v1
kind: Job
metadata:
  name: distilbert-sst2-training
spec:
  completions: 1
  parallelism: 2  # Adjust based on the number of GPUs in your cluster
  template:
    metadata:
      labels:
        app: distilbert-sst2-training
    spec:
      containers:
      - name: trainer
        image:   # Replace with your image
        resources:
          limits:
            nvidia.com/gpu: 1  # Request 1 GPU per Pod
        command: ["python", "train.py"]
      restartPolicy: Never